#!/bin/bash
# shellcheck disable=SC2034
APPNAME='resilio-sync'
APPSHORTNAME='rs'
APPPATH=''
APPTITLE='Resilio Sync'
APPDPORT=''
APPREPOSITORYNAME='resilio-sync'
ACCESSHOST='NA'
PORTSEARCH='NA'
APPSYSTEMDOVERIDE="$SCRIPTPATH/$APPNAME/$APPNAME-override.conf"
