#!/bin/bash
# shellcheck disable=SC2034
APPNAME='resilio-sync'
APPSHORTNAME='rs'
APPPATH=''
APPTITLE='resilio Sync'
APPDPORT=''
REPOPPA='NO'
REPOKEYSREQ='YES'
APPREPOSITORYNAME='resilio-sync'
ACCESSHOST='NA'
PORTSEARCH='NA'
