#!/bin/bash
APPNAME='nzbdrone'
APPSHORTNAME='sonarr'
APPPATH='/home/'$UNAME'/.nzbdrone'
APPTITLE='Sonarr / NzbDrone'
APPDEPS='mono-complete'
APPGIT=''
APPDPORT='8989'
APPSETTINGS=$APPPATH'/sabnzbd.ini'
PORTSEARCH='port = '
USERSEARCH='username = '
PASSSEARCH='password = '