#!/bin/bash
APPNAME='qbittorrent-nox'
APPSHORTNAME='qbit'
APPPATH='/home/'$UNAME'/.config/qBittorrent'
APPTITLE='qBittorrent'
APPDEPS=''
APPGIT=''
APPDPORT='8086'
APPSETTINGS=$APPPATH'/sabnzbd.ini'
PORTSEARCH='port = '
USERSEARCH='username = '
PASSSEARCH='password = '
APPREPO='ppa:qbittorrent-team/qbittorrent-stable'