#!/bin/bash
APPNAME='htpcmanager'
APPSHORTNAME='hm'
APPPATH='/opt/htpcmanager'
APPTITLE='HTPC Manager'
APPPIDFILE='/var/run/htpcmanager/htpcmanager.pid'
APPDEPS='python-imaging python-dev python-setuptools python-pip python-cherrypy vnstat python-cheetah python-pyasn1 smartmontools'
APPPIPS='psutil'
APPGIT='https://github.com/Hellowlol/HTPC-Manager'
APPDPORT='8085'
APPSETTINGSTYPE='DB'
APPSETTINGS='NA'
APPSETTINGSDB=$APPPATH'/userdata/database.db'
ACCESSHOST='NA'
PORTSEARCH='NA'
DBUSERSEARCH='SELECT val FROM setting WHERE key = "app_username";'
DBPASSSEARCH='SELECT val FROM setting WHERE key = "app_password";'
APPSYSTEMD='htpcmanager.service'
APPSYSTEMDLOC=$APPPATH'/initscripts/systemd.centOS 7'
APPINITD='htpcmanager'
APPINITDLOC=$APPPATH'/initscripts/initd'
