#!/bin/bash
APPTITLE='Mono'
APPNAME='mono-complete'
APPDEPS='libmono-cil-dev'
APPREPOSITORYNAME='mono-xamarin'
REPKEYSERVER='hkp://keyserver.ubuntu.com:80'
REPRECVKEYS='3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
REPRECVKEYSHORT='D3D831EF'
REPOPPA='NO'
APPREPOSITORYLINK='deb http://download.mono-project.com/repo/debian wheezy main'
REPOKEYSREQ='YES'
