#!/bin/bash

APPNAME='aria2'
APPSHORTNAME='a2'
APPPATH=''
APPTITLE='Aria2'
ACCESSHOST='NA'
APPSETTINGSDIR="/home/$UNAME/.config/aria2"
APPSETTINGS="$APPSETTINGSDIR/aria2.conf"
APPSYSTEMD='aria2.service'
APPSYSTEMDLOC="$SCRIPTPATH/$APPNAME/$APPSYSTEMD"
APPINITD='aria2'
APPINITDLOC="$SCRIPTPATH/$APPNAME/$APPINITD.init"

