#!/bin/bash

APPNAME='ombi'
APPSHORTNAME='ombi'
APPPATH='/opt/ombi'
APPTITLE='Ombi'
APPDEPS='libmono-cil-dev'
APPDOWNLOADURL='https://api.github.com/ombi/ombi/releases'
APPDPORT='3579'
APPSETTINGSTYPE='DB'
APPSETTINGSDIR=$APPPATH
APPSETTINGSDB=$APPSETTINGSDIR'/Ombi.sqlite'
ACCESSHOST='NA'
DBUSERSEARCH='SELECT UserName FROM Users WHERE ID = 1;'
APPSYSTEMD='ombi.service'
APPSYSTEMDLOC=$SCRIPTPATH'/ombi/'$APPSYSTEMD
APPINITD='ombi'
APPINITDLOC=$SCRIPTPATH'/ombi/ombi.init'
