#!/bin/bash

APPNAME='ombi'
APPSHORTNAME='ombi'
APPPATH='/opt/Ombi'
APPTITLE='Ombi'
APPDEPS='libunwind8 libcurl4-openssl-dev'
APPDOWNLOADURL='https://api.github.com/repos/tidusjar/Ombi/releases/latest'
APPDPORT='5000'
APPSETTINGSTYPE='DB'
APPSETTINGSDIR=$APPPATH
APPSETTINGSDB="$APPSETTINGSDIR/Ombi.db"
ACCESSHOST='NA'
DBUSERSEARCH='SELECT aspnetusers FROM Users ORDER BY ROWID ASC LIMIT 1;'
APPSYSTEMD='ombi.service'
APPSYSTEMDLOC="$SCRIPTPATH/ombi/$APPSYSTEMD"
APPINITD='ombi'
APPINITDLOC="$SCRIPTPATH/ombi/ombi.init"
