APPNAME='couchpotato'
APPSHORTNAME='cp'
APPPATH='/home/'$UNAME'/.couchpotato'
APPTITLE='CouchPotato'
APPDEPS='git-core python python-cheetah'
APPGIT='https://github.com/RuudBurger/CouchPotatoServer.git'
APPPORT='5050'