#!/bin/bash
# shellcheck disable=SC2034
APPNAME='webmin'
APPSHORTNAME='wm'
APPPATH='/etc/webmin'
APPTITLE='Webmin'
APPDPORT='10000'
APPSETTINGS=$APPPATH'/miniserv.conf'
REPOPPA='NO'
REPOKEYSREQ='YES'
APPREPOSITORYNAME='webmin'
APPREPOSITORYLINK='deb http://download.webmin.com/download/repository sarge contrib'
REPRECVKEYSASC='http://www.webmin.com/jcameron-key.asc'
REPRECVKEYSHORT='11F63C51'
APPDEFAULTUNAME='System Username'
APPDEFAULTPASS='System Password'
