#!/bin/bash
APPNAME='rutorrent'
APPSHORTNAME='ut'
APPPATH='/opt/rutorrent'
APPTITLE='ruTorrent'
APPDEPS='git screen rtorrent'
APPGIT='https://github.com/Novik/ruTorrent.git'
APPDPORT='5000'
APPSETTINGS=$APPPATH'/share/config.php'
ACCESSHOST='NA'
PORTSEARCH='NA'
USERSEARCH='NA'
PASSSEARCH='NA'
# New password encrypted
NEWPASS='atomic'
# New password unencrypted
APPNEWPASS='atomic'
APPSYSTEMD='rtorrent.service'
APPSYSTEMDLOC=$SCRIPTPATH'/rutorrent/rtorrent.service'
APPINITDLOC=$APPPATH'/runscripts/init.ubuntu'
APPDEFAULTLOC=$SCRIPTPATH'/rutorrent/rutorrent.default'
